client: name all modules
not required, makes moving modules later require changing the module
name, but some of the modules do require naming as a way to fix r.js
call error:

http://requirejs.org/docs/errors.html#mismatch
Error: Mismatched anonymous define() module: function (
         $,
         buttons,
         devtools,
         drag_n_drop,
         feedback,
         history,
         keyshortcuts,
         model_core,
         robot,
         rz_core,
         textanalysis,
         textanalysis_ui,
         util,
         filter_menu,
         search,
         selection,
         view_filter
         ) {