"use strict" must be first
Firebug 3.0 alpha or Firefox nightly 37 says:

SyntaxError: 'use strict' statement won't be enforced as a directive
because it isn't in directive prologue position